use_frameworks!

platform :ios, '9.0'

target 'TDMediator_Example' do
#  pod 'TDMediator', :path => '../'
    pod 'TDMediator',:git => 'https://github.com/shmilyfei0720/TDMediator.git'
#    pod 'TDMediator', '~> 0.1.0'

  target 'TDMediator_Tests' do
    inherit! :search_paths

    
  end
end
